import type { Review } from '../types'

// Snapshot dos jogos zerados. O sincronizador atualiza este arquivo quando a rota responde.
const jogos: Array<[string, string, number]> = [
	['god-of-war-ragnarok', 'God of War Ragnarök', 9], ['life-is-strange', 'Life Is Strange', 10], ['super-mario-odyssey', 'Super Mario Odyssey', 8], ['ghost-of-tsushima', 'Ghost of Tsushima', 9], ['kingdom-hearts-iii', 'Kingdom Hearts III', 9], ['super-mario-bros-wonder', 'Super Mario Bros. Wonder', 9], ['power-rangers-dino-thunder', 'Power Rangers: Dino Thunder', 4], ['kingdom-hearts-0-dot-2-birth-by-sleep-a-fragmentary-passage', 'Kingdom Hearts 0.2: Birth by Sleep - A Fragmentary Passage', 7], ['knights-of-the-round', 'Knights of the Round', 7], ['kingdom-hearts-birth-by-sleep-final-mix', 'Kingdom Hearts Birth by Sleep Final Mix', 9], ['hades--1', 'Hades', 6], ['ben-10-protector-of-earth', 'Ben 10: Protector of Earth', 7], ['kaze-and-the-wild-masks', 'Kaze and the Wild Masks', 7], ['batman-arkham-origins', 'Batman: Arkham Origins', 7], ['digimon-rumble-arena-2', 'Digimon Rumble Arena 2', 5], ['sonic-generations--3', 'Sonic Generations', 6], ['batman-arkham-asylum', 'Batman: Arkham Asylum', 6], ['sonic-r--2', 'Sonic R', 5], ['dragon-ball-sparking-zero', 'Dragon Ball: Sparking! Zero', 8], ['kingdom-hearts-re-chain-of-memories', 'Kingdom Hearts Re:Chain of Memories', 8], ['kingdom-hearts', 'Kingdom Hearts', 9], ['kingdom-hearts-ii', 'Kingdom Hearts II', 10], ['dragon-ball-z-budokai-3', 'Dragon Ball Z: Budokai 3', 7], ['marvel-super-heroes-in-war-of-the-gems', 'Marvel Super Heroes in War of the Gems', 7], ['mighty-morphin-power-rangers-the-fighting-edition', 'Mighty Morphin Power Rangers: The Fighting Edition', 5], ['mighty-morphin-power-rangers-the-movie', 'Mighty Morphin Power Rangers: The Movie', 6], ['mega-man-x2', 'Mega Man X2', 7], ['mega-man-x', 'Mega Man X', 8], ['dead-cells', 'Dead Cells', 7], ['stardew-valley', 'Stardew Valley', 10], ['disney-s-pk-out-of-the-shadows', "Disney's PK: Out of the Shadows", 4], ['elden-ring', 'Elden Ring', 10], ['dragon-ball-z-budokai-tenkaichi-3', 'Dragon Ball Z: Budokai Tenkaichi 3', 8], ['donkey-kong-country-3-dixie-s-kong-s-double-trouble', "Donkey Kong Country 3: Dixie Kong's Double Trouble!", 7], ['donkey-kong-country-2-diddy-s-kong-quest', "Donkey Kong Country 2: Diddy's Kong Quest", 10], ['donkey-kong-country', 'Donkey Kong Country', 8], ['chrono-trigger', 'Chrono Trigger', 10], ['hogwarts-legacy', 'Hogwarts Legacy', 10], ['pokemon-y', 'Pokémon Y', 7], ['resident-evil-4--1', 'Resident Evil 4', 10],
	['x-men-mutant-apocalypse', 'X-Men: Mutant Apocalypse', 7], ['super-mario-world', 'Super Mario World', 9], ['call-of-duty-warzone--2', 'Call of Duty: Warzone', 5], ['super-mario-bros', 'Super Mario Bros.', 6], ['super-mario-kart', 'Super Mario Kart', 5], ['disneys-goof-troop', "Disney's Goof Troop", 7], ['god-of-war', 'God of War', 7], ['we-were-here-too', 'We Were Here Too', 7], ['united-heist', 'United Heist', 6], ['we-were-here', 'We Were Here', 7], ['the-magical-quest-starring-mickey-mouse', 'The Magical Quest Starring Mickey Mouse', 6], ['minecraft-pocket-edition', 'Minecraft: Pocket Edition', 10], ['resident-evil-requiem', 'Resident Evil Requiem', 10], ['injustice-2', 'Injustice 2', 7], ['terminator-2d-no-fate', 'Terminator 2D: No Fate', 6], ['shadow-of-the-colossus', 'Shadow of the Colossus', 10], ['balatro', 'Balatro', 7], ['kingdom-hearts-dream-drop-distance-hd', 'Kingdom Hearts Dream Drop Distance HD', 7], ['sonic-generations', 'Sonic Generations', 6], ['sonic-r', 'Sonic R', 5], ['kingdom-hearts-ii-final-mix', 'Kingdom Hearts II Final Mix', 10], ['kingdom-hearts-final-mix', 'Kingdom Hearts Final Mix', 9], ['portal', 'Portal', 6], ['mortal-kombat-11', 'Mortal Kombat 11', 7], ['mortal-kombat--2', 'Mortal Kombat', 5], ['dispatch--3', 'Dispatch', 8], ['marvel-cosmic-invasion', 'Marvel Cosmic Invasion', 7], ['clair-obscur-expedition-33', 'Clair Obscur: Expedition 33', 10], ['silent-hill-2--1', 'Silent Hill 2', 10], ['minecraft--1', 'Minecraft', 10], ['star-wars-jedi-fallen-order', 'Star Wars Jedi: Fallen Order', 8], ['ultimate-spider-man', 'Ultimate Spider-Man', 6], ['super-mario-3d-world--1', 'Super Mario 3D World', 7], ['the-last-of-us-part-i', 'The Last of Us Part I', 10], ['a-short-hike', 'A Short Hike', 8], ['lego-batman-the-videogame', 'LEGO Batman: The Videogame', 7], ['the-keeper--1', 'The Keeper', 6], ['grand-theft-auto-v', 'Grand Theft Auto V', 10], ['celeste', 'Celeste', 8], ['god-of-war--1', 'God of War', 8],
]

export const reviews: Review[] = jogos.map(([slug, titulo, nota]) => ({
	slug: `backloggd-game-${slug}`,
	titulo,
	plataforma: 'Backloggd',
	nota,
	data: '2026-09-20',
	resumo: 'Jogo zerado no Backloggd.',
	tags: ['Backloggd', 'Zerados'],
	origemUrl: `https://backloggd.com/games/${slug}/`,
	corpo: [{ tipo: 'p', texto: 'Jogo zerado no Backloggd.' }],
}))
